#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "chamilo"
name = "Chamilo"
description.en = "Learning management system focused on ease of use and accessibility"
description.fr = "Système de gestion de l'apprentissage axé sur la facilité d'utilisation et l'accessibilité"

version = "1.11.32~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://chamilo.org "
demo = "https://chamilo.org/fr/demo/"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/chamilo/chamilo-lms"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/chamilo/chamilo-lms/releases/download/v2.0.0-alpha.2/chamilo-2.0.0-alpha.2.zip"
    sha256 = "d2b225d870c38e3451058e35670f78a36a93f75737c73c3f990006791a85127e"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-sqlite3, php8.4-curl, php8.4-intl, php8.4-mbstring, php8.4-xmlrpc, php8.4-mysql, php8.4-gd, php8.4-xml, php8.4-ldap, php8.4-apcu, php8.4-zip"

    [resources.database]
    type = "mysql"
